version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: fs_zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:${KAFKA_VER}
    container_name: fs_kafka_${KAFKA_VER}
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

